FROM alpine:latest                                               #pulling the latest alpine image for the dockerhub

RUN apk update && apk add wget ca-certificates && \
    cd /sbin && wget https://s3.amazonaws.com/ml-sreracha/sreracha         #updating the packages and downloding the Ca-certificats and the sreracha webapp

RUN adduser -S -H -s /bin/sh www                   #Running a shell command in Linux to add the user named www

EXPOSE 80                           #letting the docker know that the applications listens on the port 80

USER www                       #sets the user need to be used to run the docker container

ENTRYPOINT /sbin/sreracha                   #specifying which need to run first by the folder
